# Generated by Django 5.0.7 on 2024-12-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_user_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Admin',
        ),
    ]
